version: '3.0'

services:
  database:
    image: mongo:4.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME:mongoadmin
      - MONTO_INITDB_ROOT_PASSWORD:secret
      - MONGO_INITDB_DATABASE:MEANStackDB
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - backend
  express:
    build: server
    container_name: express
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - frontend
      - backend
  angular:
    build: ng6
    container_name: angular
    ports:
      - "4200:4200"
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge